# Generated by Django 5.2 on 2025-04-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='students',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Lecturers',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
